# Server Configuration

# 监听端口
PORT = 9999

# 线程池大小
THREAD_NUM = 8

# 网页根目录 
DOC_ROOT = /home/jasper/HighPerfServer/resources

# 数据库配置
DB_HOST = 127.0.0.1
DB_PORT = 5432
DB_USER = cpp_user
DB_PASS = 123456
DB_NAME = cpp_db

# 日志开关 (预留)
LOG_ENABLED = 1